
package sn.app.gsl.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSAppGSL", targetNamespace = "http://ws.gsl.app.sn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSAppGSL {


    /**
     * 
     * @return
     *     returns java.util.List<sn.app.gsl.ws.BienImmobilier>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeBIDisponible", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ListeBIDisponible")
    @ResponseWrapper(localName = "listeBIDisponibleResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ListeBIDisponibleResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/listeBIDisponibleRequest", output = "http://ws.gsl.app.sn/WSAppGSL/listeBIDisponibleResponse")
    public List<BienImmobilier> listeBIDisponible();

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "supprimerPayement", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.SupprimerPayement")
    @ResponseWrapper(localName = "supprimerPayementResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.SupprimerPayementResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/supprimerPayementRequest", output = "http://ws.gsl.app.sn/WSAppGSL/supprimerPayementResponse")
    public void supprimerPayement(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns sn.app.gsl.ws.Payement
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherPayement", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.RechercherPayement")
    @ResponseWrapper(localName = "rechercherPayementResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.RechercherPayementResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/rechercherPayementRequest", output = "http://ws.gsl.app.sn/WSAppGSL/rechercherPayementResponse")
    public Payement rechercherPayement(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authentification", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.Authentification")
    @ResponseWrapper(localName = "authentificationResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.AuthentificationResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/authentificationRequest", output = "http://ws.gsl.app.sn/WSAppGSL/authentificationResponse")
    public String authentification(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterUser", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.AjouterUser")
    @ResponseWrapper(localName = "ajouterUserResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.AjouterUserResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/ajouterUserRequest", output = "http://ws.gsl.app.sn/WSAppGSL/ajouterUserResponse")
    public void ajouterUser(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "supprimerUser", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.SupprimerUser")
    @ResponseWrapper(localName = "supprimerUserResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.SupprimerUserResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/supprimerUserRequest", output = "http://ws.gsl.app.sn/WSAppGSL/supprimerUserResponse")
    public void supprimerUser(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "modifierUser", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ModifierUser")
    @ResponseWrapper(localName = "modifierUserResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ModifierUserResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/modifierUserRequest", output = "http://ws.gsl.app.sn/WSAppGSL/modifierUserResponse")
    public void modifierUser(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @return
     *     returns java.util.List<sn.app.gsl.ws.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeUsers", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ListeUsers")
    @ResponseWrapper(localName = "listeUsersResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ListeUsersResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/listeUsersRequest", output = "http://ws.gsl.app.sn/WSAppGSL/listeUsersResponse")
    public List<User> listeUsers();

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "desactiverBI", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.DesactiverBI")
    @ResponseWrapper(localName = "desactiverBIResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.DesactiverBIResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/desactiverBIRequest", output = "http://ws.gsl.app.sn/WSAppGSL/desactiverBIResponse")
    public void desactiverBI(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param bienImmoblier
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterBI", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.AjouterBI")
    @ResponseWrapper(localName = "ajouterBIResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.AjouterBIResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/ajouterBIRequest", output = "http://ws.gsl.app.sn/WSAppGSL/ajouterBIResponse")
    public void ajouterBI(
        @WebParam(name = "bienImmoblier", targetNamespace = "")
        BienImmobilier bienImmoblier);

    /**
     * 
     * @param id
     * @return
     *     returns sn.app.gsl.ws.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherUser", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.RechercherUser")
    @ResponseWrapper(localName = "rechercherUserResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.RechercherUserResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/rechercherUserRequest", output = "http://ws.gsl.app.sn/WSAppGSL/rechercherUserResponse")
    public User rechercherUser(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param bienImmoblier
     */
    @WebMethod
    @RequestWrapper(localName = "modifierBI", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ModifierBI")
    @ResponseWrapper(localName = "modifierBIResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ModifierBIResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/modifierBIRequest", output = "http://ws.gsl.app.sn/WSAppGSL/modifierBIResponse")
    public void modifierBI(
        @WebParam(name = "bienImmoblier", targetNamespace = "")
        BienImmobilier bienImmoblier);

    /**
     * 
     * @return
     *     returns java.util.List<sn.app.gsl.ws.BienImmobilier>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeBI", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ListeBI")
    @ResponseWrapper(localName = "listeBIResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ListeBIResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/listeBIRequest", output = "http://ws.gsl.app.sn/WSAppGSL/listeBIResponse")
    public List<BienImmobilier> listeBI();

    /**
     * 
     * @param id
     * @return
     *     returns sn.app.gsl.ws.BienImmobilier
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherBI", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.RechercherBI")
    @ResponseWrapper(localName = "rechercherBIResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.RechercherBIResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/rechercherBIRequest", output = "http://ws.gsl.app.sn/WSAppGSL/rechercherBIResponse")
    public BienImmobilier rechercherBI(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param locataire
     */
    @WebMethod
    @RequestWrapper(localName = "affecterBI", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.AffecterBI")
    @ResponseWrapper(localName = "affecterBIResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.AffecterBIResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/affecterBIRequest", output = "http://ws.gsl.app.sn/WSAppGSL/affecterBIResponse")
    public void affecterBI(
        @WebParam(name = "locataire", targetNamespace = "")
        Locataire locataire);

    /**
     * 
     * @param idBI
     * @param idLoc
     */
    @WebMethod
    @RequestWrapper(localName = "libererBI", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.LibererBI")
    @ResponseWrapper(localName = "libererBIResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.LibererBIResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/libererBIRequest", output = "http://ws.gsl.app.sn/WSAppGSL/libererBIResponse")
    public void libererBI(
        @WebParam(name = "idBI", targetNamespace = "")
        int idBI,
        @WebParam(name = "idLoc", targetNamespace = "")
        int idLoc);

    /**
     * 
     * @param payement
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterPayement", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.AjouterPayement")
    @ResponseWrapper(localName = "ajouterPayementResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.AjouterPayementResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/ajouterPayementRequest", output = "http://ws.gsl.app.sn/WSAppGSL/ajouterPayementResponse")
    public void ajouterPayement(
        @WebParam(name = "payement", targetNamespace = "")
        Payement payement);

    /**
     * 
     * @return
     *     returns java.util.List<sn.app.gsl.ws.Locataire>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listeLocataires", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ListeLocataires")
    @ResponseWrapper(localName = "listeLocatairesResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ListeLocatairesResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/listeLocatairesRequest", output = "http://ws.gsl.app.sn/WSAppGSL/listeLocatairesResponse")
    public List<Locataire> listeLocataires();

    /**
     * 
     * @param payement
     */
    @WebMethod
    @RequestWrapper(localName = "modifierPayement", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ModifierPayement")
    @ResponseWrapper(localName = "modifierPayementResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ModifierPayementResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/modifierPayementRequest", output = "http://ws.gsl.app.sn/WSAppGSL/modifierPayementResponse")
    public void modifierPayement(
        @WebParam(name = "payement", targetNamespace = "")
        Payement payement);

    /**
     * 
     * @return
     *     returns java.util.List<sn.app.gsl.ws.Payement>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listePayements", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ListePayements")
    @ResponseWrapper(localName = "listePayementsResponse", targetNamespace = "http://ws.gsl.app.sn/", className = "sn.app.gsl.ws.ListePayementsResponse")
    @Action(input = "http://ws.gsl.app.sn/WSAppGSL/listePayementsRequest", output = "http://ws.gsl.app.sn/WSAppGSL/listePayementsResponse")
    public List<Payement> listePayements();

}
