
package sn.app.gsl.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSAppGSLService", targetNamespace = "http://ws.gsl.app.sn/", wsdlLocation = "http://localhost/8181/WSAppSGL?WSDL")
public class WSAppGSLService
    extends Service
{

    private final static URL WSAPPGSLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSAPPGSLSERVICE_EXCEPTION;
    private final static QName WSAPPGSLSERVICE_QNAME = new QName("http://ws.gsl.app.sn/", "WSAppGSLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/8181/WSAppSGL?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSAPPGSLSERVICE_WSDL_LOCATION = url;
        WSAPPGSLSERVICE_EXCEPTION = e;
    }

    public WSAppGSLService() {
        super(__getWsdlLocation(), WSAPPGSLSERVICE_QNAME);
    }

    public WSAppGSLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSAPPGSLSERVICE_QNAME, features);
    }

    public WSAppGSLService(URL wsdlLocation) {
        super(wsdlLocation, WSAPPGSLSERVICE_QNAME);
    }

    public WSAppGSLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSAPPGSLSERVICE_QNAME, features);
    }

    public WSAppGSLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSAppGSLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSAppGSL
     */
    @WebEndpoint(name = "WSAppGSLPort")
    public WSAppGSL getWSAppGSLPort() {
        return super.getPort(new QName("http://ws.gsl.app.sn/", "WSAppGSLPort"), WSAppGSL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSAppGSL
     */
    @WebEndpoint(name = "WSAppGSLPort")
    public WSAppGSL getWSAppGSLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gsl.app.sn/", "WSAppGSLPort"), WSAppGSL.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSAPPGSLSERVICE_EXCEPTION!= null) {
            throw WSAPPGSLSERVICE_EXCEPTION;
        }
        return WSAPPGSLSERVICE_WSDL_LOCATION;
    }

}
